### ISSUE TITLE
1.0.0 Master Checklist

### ISSUE THREAD

**Issue by brandonLi8** [brandonLi8/jessie-website#1]
# Checklist to be completed by 1.0.0:

## Design
- [ ] Design Documented Created (Date: //)
  - [ ] Mockups complete (Date: //)
  - [ ] Planned Browser Support
  - [ ] Favicon (Date: //)
  - [ ] Logo design (Date: //)
  - [ ] OG Image Preview Images
- [ ] Additional Screen Shots (Date: //)

## Implementation
- [x] Repository created (Date: //)
- [ ] [Grunt Config](https://github.com/brandonLi8/grunt-config) Added
- [ ] GitHub labels added
- [ ] Code Reviewer Identified and Completed
- [ ] Verify Credits
- [ ] Published! (Date: //)

## Testing
 - [ ] Performance acceptable on each browser (Date: //)
 - [ ] Feature Complete (Date: //)
 - [ ] iFrame support tested
 - [ ] Embedded link support
